version: "3.4"

services:
  shunidex-ui:
    image: shunidexuitw
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    command: npm start
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "0.0.0.0:3000:3000"

volumes:
  node_modules:
